### ISSUE TITLE
cmnd + shift + 3 notion does not create a number 3 heading for mac 

### ISSUE THREAD

**Issue by zluther89** [aschmelyun/use-the-keyboard#74]
This is a screenshot

**Comment by aschmelyun** [comment]
Hey @zluther89! 

Thanks a ton for this issue, all of the cmd + shift + (num) keyboard shortcuts for MacOS should have actually been cmd + opt + (num). This change also forced me to create a feature for the site that I've been putting off for a while, and that's having a complete shortcut just for MacOS instead of swapping individual keys. 

Thanks for your contribution!

**Comment by zluther89** [comment]
@aschmelyun Glad to help!!!
